---
- name: Windows File Create
  hosts: all
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  tasks:
    - name: file create
      win_file:
        path: C:\Temp\test_file_{{date}}
        state: touch
